### ISSUE TITLE
Docs: Usage

### ISSUE THREAD

**Issue by dpaez** [andrewosh/corestore-swarm-networking#1]
Hi @andrewosh 👋 I came to this module when I was looking how to properly create a swarm of hyperdrives (v10). On the datproject/sdk repo, there is a branch called `dat2` where this module [was used](https://github.com/datproject/sdk/blob/dat2/index.js#L58) to create a swarm and seed the drives.
I'm doing something similar but I don't see any connection. I've added some logs using the debug function but with no luck yet.

Any guidance/hint on how to effectively create the swarm using hyperdrive or a link to a project example can work. 

Thanks in advance!!!

**Comment by andrewosh** [comment]
Hey @dpaez, we'll be doing a big docs pass soon as part of the v10 release (which is coming together pretty quickly now).

In the meantime, maybe take a look at the way the hyperdrive daemon uses this: https://github.com/andrewosh/hyperdrive-daemon/blob/9862ed662a457de5824bc5dfc630fe8658f93b59/index.js#L57

You give it a corestore instance, and some networking options (though the defaults should be sufficient generally), then you call `listen` to start listening for connections.

To join the swarm, you can call `seed` and `unseed` with a discovery key. Importantly nothing in this module is persistent, so you have to maintain your own index of cores to seed (the daemon uses leveldb for this), and reseed everything when your process restarts.

Hope that's helpful -- there will be a lot more to work with soon.

**Comment by dpaez** [comment]
Oh thanks!, I made some progress on this front recently. I will check out the hyperdrive-daemon example, though. 
I made some tweaks to this lib to be able to handle multiple corestores (my use case involves multiples hyperdrives each one with their own corestore). 

Let me know if I can help with docs or anything. 

Once again, thanks for your answer Andrew!
